ApiTax/Entities/TourStop.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourStop
    {
        public long Id { get; set; }
        public long TourId { get; set; }
        public int CityId { get; set; }
        public Nullable<long> LocationId { get; set; }
        public short StopTypeId { get; set; }
        public short StopOrder { get; set; }
        public short Nights { get; set; }
        public Nullable<long> HotelId { get; set; }
        public Nullable<int> TransportCompanyId { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public string DepartureDateFa { get; set; }
        public System.TimeSpan DepartureTime { get; set; }
        public Nullable<int> DepartureStationId { get; set; }
        public System.TimeSpan ArrivalTime { get; set; }
        public Nullable<int> ArrivalStationId { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public Nullable<System.TimeSpan> WaitDuration { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Location Location { get; set; }
        public virtual LocCity LocCity { get; set; }
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
        public virtual Tour Tour { get; set; }
        public virtual TourStopType TourStopType { get; set; }
        public virtual TransportCompany TransportCompany { get; set; }
    }
}

ApiTax/Entities/TourStopType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourStopType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TourStopType()
        {
            this.TourStops = new HashSet<TourStop>();
        }
    
        public short Id { get; set; }
        public string Titile { get; set; }
        public string Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TourStop> TourStops { get; set; }
    }
}

ApiTax/Controllers/TourStopsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ApiTax.Entities;
using ApiTax.Models;

namespace ApiTax.Controllers
{
    public class TourStopsController : Controller
    {
        private MrTripEntities db = new MrTripEntities();

        // GET: TourStops
        public ActionResult Index(long tour_id=0)
        {
            InitRequest InitRequest = new InitRequest();
            InitRequest.init(User);

            Tour tour = db.Tours.Find(tour_id);
            if (tour == null || (tour.UserId != GlobalUser.CurrentUser.Id && GlobalUser.isAdmin == false))
            {
                return HttpNotFound();
            }

            var tourStops = db.TourStops.Where(r=>r.TourId==tour_id).Include(t => t.Hotel).Include(t => t.Location).Include(t => t.LocCity).Include(t => t.Station).Include(t => t.Station1).Include(t => t.Tour).Include(t => t.TourStopType).Include(t => t.TransportCompany);
            ViewBag.tour_id = tour_id;
            return View(tourStops.ToList());
        }

        // GET: TourStops/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TourStop tourStop = db.TourStops.Find(id);
            if (tourStop == null)
            {
                return HttpNotFound();
            }
            return View(tourStop);
        }

        // GET: TourStops/Create
        public ActionResult Create(long tour_id)
        {
            InitRequest InitRequest = new InitRequest();
            InitRequest.init(User);

            ViewBag.HotelId = new SelectList(db.Hotels, "Id", "Title");
            ViewBag.LocationId = new SelectList(db.Locations.OrderBy(r => r.Title), "Id", "Title");
            ViewBag.CityId = new SelectList(db.LocCities, "Id", "Title");
            ViewBag.DepartureStationId = new SelectList(db.Stations, "Id", "Title");
            ViewBag.ArrivalStationId = new SelectList(db.Stations, "Id", "Title");
            ViewBag.StopTypeId = new SelectList(db.TourStopTypes, "Id", "Titile");
            ViewBag.TransportCompanyId = new SelectList(db.TransportCompanies, "Id", "Title");
            ViewBag.tour_id = tour_id;

            Tour tour = db.Tours.Find(tour_id);
            if (tour == null || (tour.UserId != GlobalUser.CurrentUser.Id && GlobalUser.isAdmin == false))
            {
                return HttpNotFound();
            }

            ViewBag.ErrorMessage = "";
            return View();
        }

        // POST: TourStops/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create([Bind(Include = "Id,TourId,CityId,LocationId,StopTypeId,StopOrder,Nights,HotelId,TransportCompanyId,DepartureDate,DepartureDateFa,DepartureTime,DepartureStationId,ArrivalTime,ArrivalStationId,Duration,WaitDuration")] TourStop tourStop)
        {
            InitRequest InitRequest = new InitRequest();
            InitRequest.init(User);

            try
            {
                var date = Request.Form["DepartureDatePersian"];
                tourStop.DepartureDate = utility.ToMiladi(utility.toEnglishNumber(date.ToString()));
            }
            catch { }

            Tour tour = db.Tours.Find(tourStop.TourId);
            if (tour == null || (tour.UserId != GlobalUser.CurrentUser.Id && GlobalUser.isAdmin == false))
            {
                return HttpNotFound();
            }

            if (ModelState.IsValid)
            {
                tourStop.DepartureDateFa = utility.ToPersian(tourStop.DepartureDate.ToShortDateString());
                db.TourStops.Add(tourStop);
                db.SaveChanges();

                return RedirectToAction("Edit", "Tours", new { id = tourStop.TourId, type = "day" });
            }

            ViewBag.ErrorMessage = "به خطاها توجه نمائید";
            ViewBag.tour_id = tourStop.TourId;


            ViewBag.HotelId = new SelectList(db.Hotels, "Id", "Title", tourStop.HotelId);
            ViewBag.LocationId = new SelectList(db.Locations.OrderBy(r => r.Title), "Id", "Title", tourStop.LocationId);
            ViewBag.CityId = new SelectList(db.LocCities, "Id", "Title", tourStop.CityId);
            ViewBag.DepartureStationId = new SelectList(db.Stations, "Id", "Title", tourStop.DepartureStationId);
            ViewBag.ArrivalStationId = new SelectList(db.Stations, "Id", "Title", tourStop.ArrivalStationId);
            ViewBag.StopTypeId = new SelectList(db.TourStopTypes, "Id", "Titile", tourStop.StopTypeId);
            ViewBag.TransportCompanyId = new SelectList(db.TransportCompanies, "Id", "Title", tourStop.TransportCompanyId);
            return View(tourStop);
        }

        // GET: TourStops/Edit/5
        public ActionResult Edit(long? id)
        {
            InitRequest InitRequest = new InitRequest();
            InitRequest.init(User); 

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TourStop tourStop = db.TourStops.Find(id);
            if (tourStop == null)
            {
                return HttpNotFound();
            }

            Tour tour = db.Tours.Find(tourStop.TourId);
            if (tour == null || (tour.UserId != GlobalUser.CurrentUser.Id && GlobalUser.isAdmin == false))
            {
                return HttpNotFound();
            }

            ViewBag.ErrorMessage = "";
            ViewBag.HotelId = new SelectList(db.Hotels, "Id", "Title", tourStop.HotelId);
            ViewBag.LocationId = new SelectList(db.Locations.OrderBy(r=>r.Title), "Id", "Title", tourStop.LocationId);
            ViewBag.CityId = new SelectList(db.LocCities, "Id", "Title", tourStop.CityId);
            ViewBag.DepartureStationId = new SelectList(db.Stations, "Id", "Title", tourStop.DepartureStationId);
            ViewBag.ArrivalStationId = new SelectList(db.Stations, "Id", "Title", tourStop.ArrivalStationId);
            ViewBag.StopTypeId = new SelectList(db.TourStopTypes, "Id", "Titile", tourStop.StopTypeId);
            ViewBag.TransportCompanyId = new SelectList(db.TransportCompanies, "Id", "Title", tourStop.TransportCompanyId);
            return View(tourStop);
        }

        // POST: TourStops/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,TourId,CityId,LocationId,StopTypeId,StopOrder,Nights,HotelId,TransportCompanyId,DepartureDate,DepartureDateFa,DepartureTime,DepartureStationId,ArrivalTime,ArrivalStationId,Duration,WaitDuration")] TourStop tourStop)
        {
            InitRequest InitRequest = new InitRequest();
            InitRequest.init(User);
            try
            {
                var date = Request.Form["DepartureDatePersian"];
                tourStop.DepartureDate = utility.ToMiladi(utility.toEnglishNumber(date.ToString()));
            }
            catch { }

            Tour tour = db.Tours.Find(tourStop.TourId);
            if (tour == null || (tour.UserId != GlobalUser.CurrentUser.Id && GlobalUser.isAdmin == false))
            {
                return HttpNotFound();
            }

            if (ModelState.IsValid)
            {
                tourStop.DepartureDateFa = utility.ToPersian(tourStop.DepartureDate.ToShortDateString());
                db.Entry(tourStop).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Edit", "Tours", new { id = tourStop.TourId, type = "day" });
            }
            ViewBag.ErrorMessage = "به خطاها توجه نمائید";
            ViewBag.HotelId = new SelectList(db.Hotels, "Id", "Title", tourStop.HotelId);
            ViewBag.LocationId = new SelectList(db.Locations.OrderBy(r => r.Title), "Id", "Title", tourStop.LocationId);
            ViewBag.CityId = new SelectList(db.LocCities, "Id", "Title", tourStop.CityId);
            ViewBag.DepartureStationId = new SelectList(db.Stations, "Id", "Title", tourStop.DepartureStationId);
            ViewBag.ArrivalStationId = new SelectList(db.Stations, "Id", "Title", tourStop.ArrivalStationId);
            ViewBag.TourId = new SelectList(db.Tours, "Id", "Title", tourStop.TourId);
            ViewBag.StopTypeId = new SelectList(db.TourStopTypes, "Id", "Titile", tourStop.StopTypeId);
            ViewBag.TransportCompanyId = new SelectList(db.TransportCompanies, "Id", "Title", tourStop.TransportCompanyId);
            return View(tourStop);
        }

        // GET: TourStops/Delete/5
        public ActionResult Delete(long? id)
        {
            InitRequest InitRequest = new InitRequest();
            InitRequest.init(User);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TourStop tourStop = db.TourStops.Find(id);

            Tour tour = db.Tours.Find(tourStop.TourId);
            if (tour == null || (tour.UserId != GlobalUser.CurrentUser.Id && GlobalUser.isAdmin == false))
            {
                return HttpNotFound();
            }

            if (tourStop == null)
            {
                return HttpNotFound();
            }
            return View(tourStop);
        }

        // POST: TourStops/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            InitRequest InitRequest = new InitRequest();

ApiTax/Views/TourStops/Delete.cshtml
@model ApiTax.Entities.TourStop

@{
    ViewBag.Title = "Delete";
}

<div class="kt-portlet__head kt-portlet__head--lg">
    <div class="kt-portlet__head-label">
        <span class="kt-portlet__head-icon"><i :class="modelIcon"></i></span>
        <h3 class="kt-portlet__head-title">
            حذف روز سفر
        </h3>
    </div>
</div>
<hr />
<div class="alert alert-warning">آیا از حذف روز سفر اطمینان دارید؟</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="بلی حذف کن" class="btn btn-danger" /> |
        @Html.ActionLink("انصراف", "Edit", "Tours", new { id = Model.TourId, type = "day" }, new { @class = "btn btn-outline-info" })

    </div>

}

ApiTax/Views/TourStops/Details.cshtml
@model ApiTax.Entities.TourStop

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TourStop</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StopOrder)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StopOrder)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nights)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nights)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepartureDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartureDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepartureDateFa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartureDateFa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepartureTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartureTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ArrivalTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArrivalTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WaitDuration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WaitDuration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hotel.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hotel.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocCity.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocCity.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Station.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Station.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Station1.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Station1.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tour.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tour.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TourStopType.Titile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TourStopType.Titile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TransportCompany.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TransportCompany.Title)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ApiTax/Views/TourStops/Index.cshtml
@model IEnumerable<ApiTax.Entities.TourStop>
@using ApiTax.Models

@{
    ViewBag.Title = "جاذبه‌های تور";
    long tour_id = ViewBag.tour_id;
    Layout = null;
}

<p>
    @Html.ActionLink("اضافه کردن جاذبه/ایستگاه", "Create", "TourStops", new { tour_id = tour_id }, new { @class = "btn btn-info" })
</p>
<table class="table">
    <tr>
        <th>
           ترتیب
        </th>
        <th>
         تعداد شب
        </th>
        <th>
           تاریخ عزیمت
        </th>
        <th>
          ساعت عزیمت
        </th>
        <th>
            ساعت رسیدن
        </th>
        <th>
            مدت سفر
        </th>
        <th>
           مدت انتظار
        </th>
        <th>
            هتل محل
        </th>
        <th>
            جاذبه محل
        </th>
        <th>
            شهر
        </th>
        <th>
           ایستگاه حرکت
        </th>
        <th>
            ایستگاه رسیدن
        </th>
        <th>
           نوع روز سفر
        </th>
        <th>
           شرکت ترنسفر
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StopOrder)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nights)
            </td>
            <td>
                @utility.ToPersian(item.DepartureDate.ToShortDateString())
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepartureTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ArrivalTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WaitDuration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Hotel.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LocCity.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Station.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Station1.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TourStopType.Titile)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TransportCompany.Title)
            </td>
            <td>
                <a href="~/TourStops/Edit/@item.Id"
                   class="btn btn-sm btn-clean btn-icon btn-icon-md" title="Edit">
                    <i class="la la-edit"></i>
                </a>
                <a href="~/TourStops/Delete/@item.Id"
                   class="btn btn-sm btn-clean btn-icon btn-icon-md" title="Remove">
                    <i class="la la-trash"></i>
                </a>
            </td>
        </tr>
    }

</table>