ApiTax/Controllers/TourCouponsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ApiTax.Entities;
using ApiTax.Models;
using Newtonsoft.Json;

namespace ApiTax.Controllers
{
    public class TourCouponsController : Controller
    {
        private MrTripEntities db = new MrTripEntities();

        // GET: TourAgencyCosts
        public ActionResult Index(long tour_id = 0)
        {
            InitRequest InitRequest = new InitRequest();
            InitRequest.init(User);

            Tour tour = db.Tours.Find(tour_id);
            if (tour == null || (tour.UserId != GlobalUser.CurrentUser.Id && GlobalUser.isAdmin == false))
            {
                return HttpNotFound();
            }
            ViewBag.tour_id = tour_id;
            var tourCoupons = db.Tours.Where(r => r.Id == tour_id).Include(t => t.Coupons).FirstOrDefault().Coupons;
            return View(tourCoupons.ToList());
        }


        // GET: TourAgencyCosts/Create
        public ActionResult Create(long tour_id)
        {
            InitRequest InitRequest = new InitRequest();
            InitRequest.init(User);

            Tour tour = db.Tours.Find(tour_id);
            if (tour == null || (tour.UserId != GlobalUser.CurrentUser.Id && GlobalUser.isAdmin == false))
            {
                return HttpNotFound();
            }
            ViewBag.tour_id = tour_id;
            ViewBag.CouponId = new SelectList(db.Coupons, "Id", "Code");
            ViewBag.ErrorMessage = "";
            return View();
        }

        // POST: TourAgencyCosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TourId,CouponId")] TourCoupon TourCoupon)
        {
            InitRequest InitRequest = new InitRequest();
            InitRequest.init(User);

           
            if ( GlobalUser.isAdmin == false)
            {
                return HttpNotFound();
            }
            var coupon = db.Coupons.FirstOrDefault(r=>r.Id== TourCoupon.CouponId);

            if (ModelState.IsValid)
            {
                db.Tours.FirstOrDefault(r=>r.Id== TourCoupon.TourId).Coupons.Add(coupon);
                db.SaveChanges();
                return RedirectToAction("Edit", "Tours", new { id = TourCoupon.TourId, type = "coupon" });
            }
            ViewBag.ErrorMessage = "به خطاها توجه نمائید";
            ViewBag.CouponId = new SelectList(db.Coupons, "Id", "Code");
            ViewBag.tour_id = TourCoupon.TourId;
            return View(TourCoupon);
        }
        // GET: TourAgencyCosts/Delete/5
        public ActionResult Delete(int tour_id,int coupon_id)
        {
            InitRequest InitRequest = new InitRequest();
            InitRequest.init(User);


            if (GlobalUser.isAdmin == false)
            {
                return HttpNotFound();
            }
            Tour tour = db.Tours.Find(tour_id);
            var coupon = db.Coupons.FirstOrDefault(r => r.Id == coupon_id);
            tour.Coupons.Remove(coupon);
            db.SaveChanges();
            return RedirectToAction("Edit", "Tours", new { id = tour_id, type = "coupon" });
        }

        // POST: TourAgencyCosts/Delete/5
        [HttpPost, ActionName("Delete")]
    
        public ActionResult DeleteConfirmed(int tour_id, int coupon_id)
        {

            Tour tour = db.Tours.Find(tour_id);
            var coupon = db.Coupons.FirstOrDefault(r => r.Id == coupon_id);
            tour.Coupons.Remove(coupon);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }

}
public class TourCoupon
{
    public int TourId { get; set; }
    public int CouponId { get; set; }
}

ApiTax/Views/TourCoupons/Create.cshtml
@model TourCoupon
|@using ApiTax.Models;
@{
    ViewBag.Title = "اضافه کردن تخفیف سفر";
    long tour_id = ViewBag.tour_id;
    string error = ViewBag.ErrorMessage;
}

<div class="kt-portlet__head kt-portlet__head--lg">
    <div class="kt-portlet__head-label">
        <span class="kt-portlet__head-icon"><i :class="modelIcon"></i></span>
        <h3 class="kt-portlet__head-title">
            اضافه کردن تخفیف
        </h3>
    </div>
</div>


@if (error.Length > 0)
{
    <div class="alert alert-danger">@error</div>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <input id="TourId" name="TourId" value="@tour_id" type="hidden" />
    <div class="form-horizontal row">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.CouponId, "تخفیف ", htmlAttributes: new { @class = "control-label col-md-12" })
            <div class="col-md-10">
                @Html.DropDownList("CouponId", null, htmlAttributes: new { @class = "form-control my-multi-select" })
            </div>
        </div>

        <div class="form-group col-md-12">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ذخیره تخفیف سفر" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("بازگشت به سفر", "Edit", "Tours", new { id = tour_id, type = "coupon" }, new { @class = "btn btn-outline-info" })
</div>

ApiTax/Views/TourCoupons/Delete.cshtml
@model TourCoupon

@{
    ViewBag.Title = "Delete";
}

<div class="kt-portlet__head kt-portlet__head--lg">
    <div class="kt-portlet__head-label">
        <span class="kt-portlet__head-icon"><i :class="modelIcon"></i></span>
        <h3 class="kt-portlet__head-title">
            حذف تخفیف سفر
        </h3>
    </div>
</div>
<hr />
<div class="alert alert-warning">آیا از حذف تخفیف سفر اطمینان دارید؟</div>

<form>
    <input id="tour_id" name="tour_id" type="hidden" value="@Model.TourId" />
    <input id="coupon_id" name="coupon_id" type="hidden" value="@Model.CouponId" />


    <div class="form-actions no-color">
        <input type="submit" value="بلی حذف کن" class="btn btn-danger" /> |
        @Html.ActionLink("انصراف", "Edit", "Tours", new { id = Model.TourId, type = "coupon" }, new { @class = "btn btn-outline-info" })

    </div>
</form>

ApiTax/Views/TourCoupons/Index.cshtml
@model IEnumerable<ApiTax.Entities.Coupon>

@{
    ViewBag.Title = "Index";
    long tour_id = ViewBag.tour_id;
    Layout = null;
}

<p>
    @Html.ActionLink("اضافه کردن تخفیف سفر", "Create", "TourCoupons", new { tour_id = tour_id }, new { @class = "btn btn-info" })
</p>
<table class="table">
    <tr>
        <th>
            تخفیف
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Code)
    </td>
    <td>
        <a href="~/TourCoupons/Delete?tour_id=@tour_id&coupon_id=@item.Id"
           class="btn btn-sm btn-clean btn-icon btn-icon-md" title="Remove">
            <i class="la la-trash"></i>
        </a>
    </td>
</tr>
}

</table>